<?php
/**
 * Implements hook_services_resources().
 */

function custom_services_services_resources(){
	return array(
	    'page' => array(
	        'operations' => array(
	            'index' => array(
                    'help' => 'Return a page data',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'page_resource'),
                    'callback' => 'page_resource_index',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'args',
                            'type' => 'string',
                            'description' => 'Arguments of page',
                            'source' => array('param' => 'args'),
                            'optional' => True,
                            'default' => 'home'
                        ),
                    )
                )
            ),
            'actions' => array(
                'contact_form' => array(
                    'help' => 'Contact us form page',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'page_resource'),
                    'callback' => 'page_resource_contact_form',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'The data of request.',
                            'source' => 'data',
                            'optional' => False,
                        ),
                    ),
                ),
            ),
        ),
        'user' => array(
            'operations' => array(
                'update' => array(
                    'help' => 'Update a user',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_update_data',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'optional' => FALSE,
                            'source' => 'data',
                            'description' => 'The profile data to update',
                            'type' => 'array',
                        ),
                        array(
                            'name' => 'uid',
                            'optional' => FALSE,
                            'source' => array('path' => 0),
                            'type' => 'int',
                            'description' => 'The uid of the user',
                        ),
                    ),
                ),
            ),
            'actions' => array(
                'login' => array(
                    'help' => 'Login a user for a new session',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_login',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'The data of request.',
                            'source' => 'data',
                            'optional' => False,
                        ),
                    ),
                ),
                'register' => array(
                    'help' => 'Create a new user',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_register',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'The hash of url.',
                            'source' => 'data',
                            'optional' => False,
                        ),
                    ),
                ),
                'exist' => array(
                    'help' => 'Check user is exist or not!',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_exist',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'User data',
                            'source' => 'data',
                            'optional' => FALSE,
                        ),
                    ),
                ),
                'subscribe_email' => array(
                    'help' => 'Insert the user`s Email',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_subscribe_email',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'User data',
                            'source' => 'data',
                            'optional' => FALSE,
                        ),
                    ),
                ),
            ),
            'relationships' => array(
                'information' => array(
                    'help' => 'Return user`s data',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_information',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'Parameters of request.',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                        array(
                            'name' => 'uid',
                            'optional' => FALSE,
                            'source' => array('path' => 0),
                            'type' => 'int',
                            'description' => 'The uid of the user',
                        ),
                    ),
                ),
                'nav_bar_info' => array(
                    'help' => 'Return user`s data for nav bar',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'user_resource'),
                    'callback' => 'user_resource_nav_bar_info',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'Parameters of request.',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                        array(
                            'name' => 'login',
                            'optional' => FALSE,
                            'source' => array('path' => 0),
                            'type' => 'string',
                            'description' => 'Just for create url',
                        ),
                    ),
                ),
            ),
        ),
        'latin_contents' => array(
            'operations' => array(
                'index' => array(
                    'help' => 'return all contents',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'latin_contents_resource'),
                    'callback' => 'latin_contents_resource_index',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'Parameters of request.',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                    ),
                ),
                'retrieve' => array(
                    'help' => 'return a contents',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'latin_contents_resource'),
                    'callback' => 'latin_contents_resource_retrieve',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'Parameters of request.',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                        array(
                            'name' => 'nid',
                            'type' => 'int',
                            'description' => 'Nid of content',
                            'source' => array('path' => 0),
                            'optional' => FALSE,
                        ),
                    ),
                ),
            ),
            'relationships' => array(
                'filters' => array(
                    'help' => 'return filters of a content type',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'latin_contents_resource'),
                    'callback' => 'latin_contents_resource_filters',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'Parameters of request.',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                        array(
                            'name' => 'type',
                            'type' => 'string',
                            'description' => 'Just use for url address.',
                            'source' => array('path' => 0),
                            'optional' => False,
                            'default' => "all"
                        ),
                    ),
                ),
            ),
        ),
        'tag' => array(
            'operations' => array(
                'index' => array(),
                'retrieve' => array(),
            ),
            'relationships' => array(
                'contents' => array(
                    'help' => 'return all contents of a tag',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'tag_resource'),
                    'callback' => 'tag_resource_contents',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'Parameters of request.',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                        array(
                            'name' => 'tid',
                            'optional' => FALSE,
                            'source' => array('path' => 0),
                            'type' => 'int',
                            'description' => 'The tid of the tag',
                        ),
                    ),
                ),
            ),
        ),
        'file' => array(
            'actions' => array(
                'upload' => array(
                    'help' => 'Upload a file with raw data.',
                    'callback' => 'upload_file',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'The hash of url.',
                            'source' => array('param' => 'parameter'),
                            'optional' => False,
                        ),
                    ),
                ),
            ),
        ),
        'flag' => array(
            'operations' => array(
                'create' => array(
                    'help' => 'bookmark a content or taxonomy',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'flag_resource'),
                    'callback' => 'flag_resource_create',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'Bookmark or un-bookmark a node or taxonomy',
                            'source' => 'data',
                            'optional' => FALSE,
                        )
                    ),
                ),
            ),
        ),
        'event' => array(
            'operations' => array(
                'index' => array(
                    'help' => 'Return event list',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'event_resource'),
                    'callback' => 'event_resource_index',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'parameter of api',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                    )
                ),
                'retrieve' => array(
                    'help' => 'Return a event data',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'event_resource'),
                    'callback' => 'event_resource_retrieve',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'nid',
                            'type' => 'int',
                            'description' => 'parameter of api',
                            'source' => array('path' => 0),
                            'optional' => False,
                        ),
                        array(
                            'name' => 'parameter',
                            'type' => 'array',
                            'description' => 'parameter of api',
                            'source' => array('param' => 'parameter'),
                            'optional' => True,
                            'default' => array()
                        ),
                    )
                ),
            ),
        ),
        'post' => array(
            'operations' => array(
                'index' => array(),
                'create' => array(
                    'help' => 'Create a post',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'post_resource'),
                    'callback' => 'post_resource_create',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'data',
                            'type' => 'array',
                            'description' => 'data of api',
                            'source' => 'data',
                            'optional' => False
                        ),
                    )
                ),
                'update' => array(),
                'retrieve' => array(),
                'delete' => array(),
            ),
        ),

        'latin_news' => array(
            'operations' => array(
                'index' => array(
                    'help' => 'return all latin news',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'latin_news_resource'),
                    'callback' => 'latin_news_resource_index',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                ),
                'retrieve' => array(
                    'help' => 'retrieve a latin news',
                    'file' => array('type' => 'inc', 'module' => 'custom_services', 'name' => 'latin_news_resource'),
                    'callback' => 'latin_news_resource_retrieve',
                    'access callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' => array(
                        array(
                            'name' => 'nid',
                            'optional' => FALSE,
                            'source' => array('path' => 0),
                            'type' => 'int',
                            'description' => 'The nid of the news to retrieve',
                        ),
                    ),
                ),
            ),
        ),
	);
}
function upload_file($parameter) {
    if(!isset($parameter["hash"]) || !(hash_true($parameter["hash"] , "file"))) return services_error(t('Failed to access'), 10);
    global $user;
    if($user == 0) return services_error(t('You should be login!'), 13);
    $files =  $_FILES;
    foreach ($files as $file_name => $file_info){
        $_FILES["files"]["name"][$file_name] = $file_info['name'];
        $_FILES["files"]["tmp_name"][$file_name] = $file_info['tmp_name'];
        $_FILES["files"]["size"][$file_name] = $file_info['size'];
        $_FILES["files"]["error"][$file_name] = $file_info['error'];
    }
    $files = array();
    foreach ($_FILES['files']['name'] as $field_name => $file_name) {
        // Sanitize the user-input file name before saving to the file system.
        $_FILES['files']['name'][$field_name] = _services_file_check_name_extension($file_name);

        $scheme = file_default_scheme();
        // Set file validators: allowed extension
        $validators = array();
        if ($extensions = variable_get('services_allowed_extensions', SERVICES_ALLOWED_EXTENSIONS)) {
            $validators['file_validate_extensions'] = $extensions;
        }
        $file = file_save_upload($field_name, $validators, "$scheme://");

        if (!empty($file->fid)) {
            // Change the file status from temporary to permanent.
            $file->status = FILE_STATUS_PERMANENT;
            file_save($file);

            // Required to be able to reference this file.
            file_usage_add($file, 'services', 'files', $file->fid);

            $files[$field_name] = $file;
        }
        else {
            return services_error(t('An unknown error occured'), 500);
        }
    }
    return $files;
}

function hash_true($hash , $resource){
    $new_hash = hash_hmac("sha256" , $resource , "@Civil808Android@Saze808@" , false);
    if(strcmp($hash, $new_hash) == 0) return true;
    return false;
}
function generate_file_address($url){
    $url = substr($url , 8);
    $url = "http://api.ed808.com/sites/default/files" . $url;
    return $url;
}